version: "3.7"
services:
  dns:
    build: .
    image: homecentr/dns
    dns:
      - 127.0.0.1 # important for health check
    restart: unless-stopped
    volumes:
      - "./example:/config:rw"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "953:953/tcp"
      - "8888:8888/tcp"