name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag homecentr-dns:${{ steps.vars.outputs.docker_tag }}
      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@master
      # - name: Scan with Phonito Security
      #   uses: phonito/phonito-scanner-action@master
      #   with:
      #     image: homecentr-dns:${{ steps.vars.outputs.docker_tag }}
      #     phonito-token: '${{ secrets.PHONITO_TOKEN }}'      


      - name: Scan image with Anchore
        uses: anchore/scan-action@master
        with:
          image-reference: "homecentr-dns:${{ steps.vars.outputs.docker_tag }}"
          dockerfile-path: "./Dockerfile"
          fail-build: true
      - name: Anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done