name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker image
        run: docker build . -t local/dns:latest
      - name: Verify Dockerfile with Hadolint
        uses: brpaz/hadolint-action@master
      - name: Scan image with Anchore
        uses: anchore/scan-action@master
        with:
          image-reference: "local/dns:latest"
          dockerfile-path: "./Dockerfile"
          fail-build: true
      - name: Anchore inline scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done