name: CI PR/Branch
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build . -t homecentr/dns:feature
      - uses: anchore/scan-action@master
        with:
          image-reference: "homecentr/dns:feature"
          dockerfile-path: "./Dockerfile"
          fail-build: true
          include-app-packages: true